version: '3'
services:
  frontend:
    build:
      # Use the current directory as the build context
      # This allows us to access the files in the current directory inside the Dockerfile
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      # Expose port 8080 on the host, and map port 3000 of the container to port 8080 on the host
      - "8080:3000"
    volumes:
      # Mount the frontend directory to the /app directory in the container
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    networks:
      - book_system_network
  orchestrator:
    build:
      context: ./service-orchestrator/
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - book_system_network
  fraud-detection:
    build:
      context: ./service-fraud-detection/
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    networks:
      - book_system_network
  transaction-verification:
    build:
      context: ./service-transaction-verification/
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    networks:
      - book_system_network
  suggestion-service:
    build:
      context: ./service-suggestion-service/
      dockerfile: Dockerfile
    ports:
      - "50053:50053"
    networks:
      - book_system_network
  order-queue-service:
    build:
      context: ./service-order-queue/
      dockerfile: Dockerfile
    ports:
      - "50054:50054"
    networks:
      - book_system_network
  coordinator-service:
    build:
      context: ./service-coordinator/
      dockerfile: Dockerfile
    ports:
      - "50055:50055"
    networks:
      - book_system_network
  executor-service:
    build:
      context: ./service-executor/
      dockerfile: Dockerfile
    ports:
      - "50060:50060"
    networks:
      - book_system_network
  database-service:
    build:
      context: ./service-database/
      dockerfile: Dockerfile
    ports:
      - "50090:50090"
    networks:
      - book_system_network
  payment-service:
    build:
      context: ./service-payment/
      dockerfile: Dockerfile
    ports:
      - "50100:50100"
    networks:
      - book_system_network

networks:
  book_system_network:
    driver: bridge