server:
  port: 8081
spring:
  application:
    name: grpc-client
  task:
    execution:
      pool:
        core-size: 2
        max-size: 3
grpc:
  client:
    grpc-fraud-detection:
      address: 'static://fraud_detection:50051'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    grpc-transaction-verification:
      address: 'static://transaction_verification:50052'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    grpc-suggestion-service:
      address: 'static://suggestion_service:50053'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    grpc-order-queue:
      address: 'static://order_queue_service:50054'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext


vectorclock:
  nodeId: orchestrator

