server:
  port: 8081
spring:
  application:
    name: grpc-client
  task:
    execution:
      pool:
        core-size: 2
        max-size: 3
  sleuth:
    otel:
      exporter:
        otlp:
          endpoint: 'http://observability:4317'
      config:
        trace-id-ratio-based: 1.0
grpc:
  client:
    grpc-fraud-detection:
      address: 'fraud-detection:50051'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    grpc-transaction-verification:
      address: 'transaction-verification:50052'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    grpc-suggestion-service:
      address: 'suggestion-service:50053'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    grpc-order-queue:
      address: 'order-queue-service:50054'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext


vectorclock:
  nodeId: orchestrator
