grpc:
  server:
    port: 50060

vectorclock:
  nodeId: executor


  grpc:
    client:
      grpc-payment-service:
        address: 'static://127.0.0.1:50100'
        enableKeepAlive: true
        keepAliveWithoutCalls: true
        negotiationType: plaintext

        grpc-database-service:
          address: 'static://127.0.0.1:50090'
          enableKeepAlive: true
          keepAliveWithoutCalls: true
          negotiationType: plaintext